### ISSUE TITLE
Fatal Exception: android.view.InflateException: Binary XML file line #2: Error inflating class com.lany.picker.DatePicker

### ISSUE THREAD

**Issue by vladimirfx** [lany192/DateTimePicker#3]
It is known problem of platform for some locale/vendor combination. As workaround you may catch exception when call DateFormat.getDateFormatOrder and choose some default order.

Relevant part of stack trace:
`
Caused by java.lang.IllegalArgumentException: Bad pattern character 'E' in E, d MMM yyyy
       at libcore.icu.ICU.getDateFormatOrder(ICU.java:314)
       at android.text.format.DateFormat.getDateFormatOrder(DateFormat.java:389)
       at com.lany.picker.DatePicker.reorderNPickers(DatePicker.java:399)
       at com.lany.picker.DatePicker.<init>(DatePicker.java:202)
       at com.lany.picker.DatePicker.<init>(DatePicker.java:74)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at com.astroid.yodha.customer.ProfileFragment$onViewCreated$dateClicker$1.onClick(ProfileFragment.java:173)
       at com.astroid.yodha.ViewExtKt$onClickWithDebounce$1.onClick(ViewExtKt.java:52)
       at android.view.View.performClick(View.java:4807)
       at android.view.View$PerformClick.run(View.java:20106)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5576)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
`

**Comment by lany192** [comment]
thanks
